var titre = document.getElementsByTagName('h1');
console.log(titre);
for (var test=0; test<titre.length; test++){
	if (test%2==0) {
    titre[test].style.background='pink';
	}

else{
	titre[test].style.background='blue';

}
}

//var test1 = document.getElementById("test1");
//console.log(test1);
/*test1.addEventListener("mouseenter", function(event) {
	event.target.style.color = "orange";}*/
/*var resultat= function()
{console.log("resultat");
}*/
/*var resultat = function (Numero1,Numero2){
	console.log(resultat);

}
var addition=function(Numero1,Numero2){
	return Numero1+Numero2;
}
var soustraction=function(Numero1,Numero2){
	return Numero1-Numero2;
}
var multiplication=function(Numero1,Numero2){
	return Numero1*Numero2;
}
var division=function(Numero1,Numero2){
	return Numero1/Numero2;
}
var modulo=function(Numero1,Numero2){
	return Numero1%Numero2;
}*/
//µµµµµµµµµµµµµµµµµµµµµµµµµµµµµµµµµµµµµµµµµµµµµµµµ
//EXO3 
var identite = document.getElementsByClassName(".identite");
console.log(identite);

/*for var controle=0; test<titre.length; test++){
	if (test%2==0) {
    titre[test].style.background='pink';
	}*/
